package com.practice.calendar.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF3C6480)
val LightSecondary = Color(0xFF54606B)
val LightTertiary = Color(0xFF3C5F8F)
val LightBackground = Color(0xFFFAFBFD)
val LightSurface = Color(0xFFFAFBFD)
val LightOnPrimary = Color(0xFFFEFEFE)
val LightOnSecondary = Color(0xFFFEFEFE)
val LightOnTertiary = Color(0xFFFEFEFE)
val LightOnBackground = Color(0xFF1A1C1E)
val LightOnSurface = Color(0xFF1A1C1E)
val LightPrimaryContainer = Color(0xFFCCE6FC)
val LightOnPrimaryContainer = Color(0xFF0E1E29)
val LightSecondaryContainer = Color(0xFFD7E4F0)
val LightOnSecondaryContainer = Color(0xFF121D26)
val LightTertiaryContainer = Color(0xFFD3E3FC)
val LightOnTertiaryContainer = Color(0xFF0E1C2F)
val LightOutlined = Color(0xFF73787D)
val LightSurfaceVariant = Color(0xFFDEE3E8)
val LightOnSurfaceVariant = Color(0xFF43484C)

val DarkPrimary = Color(0xFF95CEFA)
val DarkSecondary = Color(0xFFBBC8D4)
val DarkTertiary = Color(0xFFA6C8FA)
val DarkBackground = Color(0xFF1A1C1E)
val DarkSurface = Color(0xFF1A1C1E)
val DarkOnPrimary = Color(0xFF1C3345)
val DarkOnSecondary = Color(0xFF27323B)
val DarkOnTertiary = Color(0xFF1D314D)
val DarkOnBackground = Color(0xFFE0E1E3)
val DarkOnSurface = Color(0xFFE0E1E3)
val DarkPrimaryContainer = Color(0xFF2C4B62)
val DarkOnPrimaryContainer = Color(0xFFCCE6FC)
val DarkSecondaryContainer = Color(0xFF3D4952)
val DarkOnSecondaryContainer = Color(0xFFD7E4F0)
val DarkTertiaryContainer = Color(0xFF2C476E)
val DarkOnTertiaryContainer = Color(0xFFD3E3FC)
val DarkOutlined = Color(0xFF8C9196)
val DarkSurfaceVariant = Color(0xFF43484C)
val DarkOnSurfaceVariant = Color(0xFFC2C7CC)
